adding new url
community/community pull request #17838
Opened 2022-06-02 23:15 UTC by natalierjackson

2022-06-02 23:17 UTC, natalierjackson reviewed
update url

2022-06-02 23:19 UTC, michellemerrill requested changes
@natalierjackson Please add in `GitHub Education` category -- and `Polls` too.

2022-06-02 23:38 UTC, michellemerrill approved these changes
LGTM

2022-06-03 01:28 UTC, merged

2024-07-26 14:06 UTC, 7738005772 commented
> _No se proporcionó descripción._
Discusión