update readme copy
community/community pull request #20600
Opened 2022-07-15 13:51 UTC by tuves

2022-07-15 20:51 UTC, jenna-wolf requested changes
Referencing [my feedback](https://github.com/github-community/community/pull/20600/commits/197c30c3d614435d0c7014668e4a23c6f3cceb3d#r922506657) to a URL here, I think this applies to all URLs in this PR referencing the new org name. Should we just have at top level org discussions, or directly in the repo Discussions? The org level discussions will look nicer. 

@ettaboyle @tuves @michellemerrill @natalierjackson

2022-07-19 07:50 UTC, Aa0541599451 commented on README.md
> +| 👍  [Accessibility](https://github.com/community/discussions/categories/accessibility) 	| [About Accessibility](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-a
[](https://github.com/Aa0541599451/Aa0541599451-.git)

2022-07-19 07:52 UTC, Aa0541599451 commented
انا

2022-07-19 07:54 UTC, Aa0541599451 commented on README.md
> +| 👍  [Accessibility](https://github.com/community/discussions/categories/accessibility) 	| [About Accessibility](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-a
- [ ] [](https://github.com/github-community/community/pull/20600#pullrequestreview-1040791342)
- - 
@Aa0541599451 @https://github.com/github-community/community/pull/20600#pullrequestreview-1040791342

2022-07-23 13:10 UTC, MohamudMmc reviewed
👍

2022-07-23 13:13 UTC, zayidmohamedy reviewed
👍

2022-07-25 18:30 UTC, ettaboyle commented on README.md
> +| 👍  [Accessibility](https://github.com/community/discussions/categories/accessibility) 	| [About Accessibility](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-a
https://github.com/orgs/community/discussions/categories/announcements is an example of the actual URL structure post org rename for category links

2022-07-25 18:39 UTC, ettaboyle approved these changes
Approved

2022-07-25 18:39 UTC, ettaboyle commented on README.md
> +We encourage you to [open a discussion](https://github.com/community) if you have suggestions for how we can improve our products. You don't need to have a solution to the problem you are facing to k
```suggestion
We encourage you to [open a discussion](https://github.com/orgs/community/discussions) if you have suggestions for how we can improve our products. You don't need to have a solution to the problem you are facing to kick off a discussion. We hope to foster productive and collaborative conversations, so please check out [how to give good feedback](https://github.com/community/discussions/1) for guidance on how to kick off a successful discussion.
```

2022-07-25 18:41 UTC, ettaboyle commented
[HOLD] Do not merge until we update org url

2022-07-26 05:08 UTC, Mystic421980 commented
> [HOLD] Do not merge until we update org url

SigTerm

2022-07-26 05:11 UTC, Mystic421980 commented
> > [HOLD] Do not merge until we update org url
> 
> SigTerm

Run

2022-07-27 14:01 UTC, ettaboyle approved these changes

2022-07-27 14:11 UTC, merged