Update Category Forms for Accessibility and API & Webhooks
community/community pull request #49004
Opened 2023-03-02 17:31 UTC by ghostinhershell

Removed <title> def and updated the topic order for the API & Webhooks and Accessibility category forms.

2023-03-06 10:00 UTC, Alokrar commented
See

2023-03-06 16:05 UTC, otter-computer requested changes
You'll need to remove the whole line here, not just change it to a blank space!

2023-03-06 16:05 UTC, otter-computer commented on .github/DISCUSSION_TEMPLATE/accessibility.yml
> +title: " "
```suggestion
```

2023-03-06 16:05 UTC, otter-computer commented on .github/DISCUSSION_TEMPLATE/api-and-webhooks.yml
> +title: " "
```suggestion
```

2023-03-06 19:18 UTC, roymoses07 commented on .github/DISCUSSION_TEMPLATE/api-and-webhooks.yml
> +title: " "
Moses Ojero

2023-03-07 03:25 UTC, Alokrar commented
Thanks

On Tue, Mar 7, 2023, 12:49 AM Moses Okeoghene Ojero <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/DISCUSSION_TEMPLATE/api-and-webhooks.yml
> <https://github.com/community/community/pull/49004#discussion_r1126919516>
> :
>
> > @@ -1,13 +1,13 @@
> -title: "<title>"
> +title: " "
>
> Moses Ojero
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/community/community/pull/49004#discussion_r1126919516>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS7LEX7UOUGN2NBBQUC3VG3W2Y2DBANCNFSM6AAAAAAVNVNH2M>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-07 05:11 UTC, perezz281 reviewed
#49380

2023-03-07 18:25 UTC, comet19950902 commented
As I can see, good.
Thank you.

2023-03-12 06:47 UTC, SuphathatUdomkan commented
ghostinhershell-category-form-update

2023-03-13 04:53 UTC, dirrthick commented
https://github.com/blockchain/My-Wallet-V3-iOS/compare/v202212.1.2-rc.13742...v202301.2.0-rc.13885

2023-03-13 17:17 UTC, P-Tanawat reviewed
[![Auto Close PRs](https://github.com/community/community/actions/workflows/auto-close-pr.yml/badge.svg)](https://github.com/community/community/actions/workflows/auto-close-pr.yml)
[react-new](https://codesandbox.io/embed/react-new?fontsize=14&hidenavigation=1&theme=light) 
.diff

2023-03-13 17:17 UTC, P-Tanawat commented on .github/DISCUSSION_TEMPLATE/accessibility.yml
> +title: " "
[![Auto Close PRs](https://github.com/community/community/actions/workflows/auto-close-pr.yml/badge.svg)](https://github.com/community/community/actions/workflows/auto-close-pr.yml)
.diff

2023-03-13 17:17 UTC, P-Tanawat commented on .github/DISCUSSION_TEMPLATE/api-and-webhooks.yml
> +title: " "
```[![Auto Close PRs](https://github.com/community/community/actions/workflows/auto-close-pr.yml/badge.svg)](https://github.com/community/community/actions/workflows/auto-close-pr.yml)
title: "Auto Close PRs"
```

2023-03-13 22:34 UTC, TOUFIKTOUHAMI commented
y

2023-03-13 22:38 UTC, TOUFIKTOUHAMI commented
@
Duplicate of #sq

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-13 22:39 UTC, TOUFIKTOUHAMI commented
sasa

2023-03-14 03:07 UTC, Mroczek1992 commented on .github/DISCUSSION_TEMPLATE/api-and-webhooks.yml
> +      - "Product Feedback"
Chciałbym bym porozmawiać

2023-03-14 11:51 UTC, merged

2023-03-20 06:06 UTC, Nward8118 reviewed
Duplicate of #

> t`
Nicholasward81@gmail.com `